import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import Nav from "@/app/components/Nav";
// import Footer from "./components/Footer";
// import Nav from "@/components/Nav"
import Nav from "@/components/Nav"
// import Footer from "@/components/Footer";
import Footer from "@/components/Footer";
import { CartProvider } from "./context/cartContext";
import { WishlistProvider } from "./context/WishlistContext";
import { UserProvider } from "./context/UserContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      ><Nav />
        <CartProvider>
          <WishlistProvider>
            <UserProvider>{children}</UserProvider>
            </WishlistProvider>
        </CartProvider>
        <Footer />
      </body>
    </html>
  );
}
